modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="mcas" #mandatory

version="1.0.0" #mandatory

displayName="More Constellations - AS" #mandatory

# updateJSONURL="http://myurl.me/" #optional

# displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Thanks to the Astral Sorcery devs." #optional

authors="Gekocaretaker" #optional

description='''
This is a extension of Astral Sorcery to add more Constellations to the game!
'''

[[dependencies.mcas]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.mcas]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

#[[dependencies.mcas]]
#    modId="astralsorcery"
#    mandatory=true
#    versionRange="[1.15.2-1.12.13.v246]"
#    ordering="NONE"
#    sides="BOTH"

[[dependencies.mcas]]
    modId="observerlib"
    mandatory=true
    versionRange="[1.15.2-1.3,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcas]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.2-,)"
    ordering="NONE"
    side="BOTH"